name: Backend CI

on:
  push:
    paths:
      - 'Microservices/backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'Microservices/backend/**'
      - '.github/workflows/backend-ci.yml'

defaults:
  run:
    working-directory: Microservices/backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npm test
