name: Docker Publish

on:
  push:
    branches: ['main']
    paths:
      - 'Microservices/frontend/**'
      - 'Microservices/backend/**'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Frontend Docker Image
        working-directory: Microservices/frontend
        run: docker build -t yourusername/blog-frontend:latest .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Frontend Image
        run: docker push yourusername/blog-frontend:latest

  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Backend Docker Image
        working-directory: Microservices/backend
        run: docker build -t nana1212/blog-backend:latest .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Backend Image
        run: docker push nana1212/blog-backend:latest
